// <auto-generated />
using System;
using BookingRoomHotel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingRoomHotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126124437_CreateMigration")]
    partial class CreateMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookingRoomHotel.Models.CauHoi", b =>
                {
                    b.Property<int>("MaCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHoi"), 1L, 1);

                    b.Property<string>("ChuDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhanHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaCauHoi");

                    b.ToTable("CauHois");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"), 1L, 1);

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sao")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.DatDichVu", b =>
                {
                    b.Property<int>("MaDatDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatDichVu"), 1L, 1);

                    b.Property<int>("DatPhongMaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("DichVuMaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("MaDatDichVu");

                    b.HasIndex("DatPhongMaDatPhong");

                    b.HasIndex("DichVuMaDichVu");

                    b.ToTable("DatDichVus");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.DatPhong", b =>
                {
                    b.Property<int>("MaDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatPhong"), 1L, 1);

                    b.Property<string>("KhachHangMaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraPhong")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongMaPhong")
                        .HasColumnType("int");

                    b.Property<int?>("TongTien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDatPhong");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.HasIndex("PhongMaPhong");

                    b.ToTable("DatPhongs");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"), 1L, 1);

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AnhCMND1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnhCMND2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.KhachSan", b =>
                {
                    b.Property<int>("MaKhachSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachSan"), 1L, 1);

                    b.Property<int>("DanhGia")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhachSan");

                    b.ToTable("KhachSans");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"), 1L, 1);

                    b.Property<int>("DienTich")
                        .HasColumnType("int");

                    b.Property<int>("GiaDen")
                        .HasColumnType("int");

                    b.Property<int>("GiaTu")
                        .HasColumnType("int");

                    b.Property<string>("Huong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoGiuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.Media", b =>
                {
                    b.Property<int>("MaMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMedia"), 1L, 1);

                    b.Property<string>("DungCho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoaiPhongMaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMedia");

                    b.HasIndex("LoaiPhongMaLoaiPhong");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"), 1L, 1);

                    b.Property<string>("AnhPhong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DichVuMaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<int?>("KhachSanMaKhachSan")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiPhongMaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoPhong")
                        .HasColumnType("int");

                    b.HasKey("MaPhong");

                    b.HasIndex("DichVuMaDichVu");

                    b.HasIndex("KhachSanMaKhachSan");

                    b.HasIndex("LoaiPhongMaLoaiPhong");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.ThongBaoKhachHang", b =>
                {
                    b.Property<int>("MaThongBaoKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBaoKhachHang"), 1L, 1);

                    b.Property<string>("KhachHangMaKhachHang")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThongBaoKhachHang");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.ToTable("ThongBaoKhachHangs");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.ThongBaoNhanVien", b =>
                {
                    b.Property<int>("MaThongBaoNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBaoNhanVien"), 1L, 1);

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNhanVien")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThongBaoNhanVien");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("ThongBaoNhanVien");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.DatDichVu", b =>
                {
                    b.HasOne("BookingRoomHotel.Models.DatPhong", "DatPhong")
                        .WithMany("DatDichVus")
                        .HasForeignKey("DatPhongMaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoomHotel.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuMaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.DatPhong", b =>
                {
                    b.HasOne("BookingRoomHotel.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoomHotel.Models.Phong", "Phong")
                        .WithMany("DatPhongs")
                        .HasForeignKey("PhongMaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.Media", b =>
                {
                    b.HasOne("BookingRoomHotel.Models.LoaiPhong", null)
                        .WithMany("Media")
                        .HasForeignKey("LoaiPhongMaLoaiPhong");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.Phong", b =>
                {
                    b.HasOne("BookingRoomHotel.Models.DichVu", null)
                        .WithMany("Phongs")
                        .HasForeignKey("DichVuMaDichVu");

                    b.HasOne("BookingRoomHotel.Models.KhachSan", "KhachSan")
                        .WithMany("Phongs")
                        .HasForeignKey("KhachSanMaKhachSan");

                    b.HasOne("BookingRoomHotel.Models.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("LoaiPhongMaLoaiPhong");

                    b.Navigation("KhachSan");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.ThongBaoKhachHang", b =>
                {
                    b.HasOne("BookingRoomHotel.Models.KhachHang", null)
                        .WithMany("ThongBaoKhachHang")
                        .HasForeignKey("KhachHangMaKhachHang");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.ThongBaoNhanVien", b =>
                {
                    b.HasOne("BookingRoomHotel.Models.NhanVien", null)
                        .WithMany("ThongBaoNhanVien")
                        .HasForeignKey("NhanVienMaNhanVien");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.DatPhong", b =>
                {
                    b.Navigation("DatDichVus");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.DichVu", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.KhachHang", b =>
                {
                    b.Navigation("ThongBaoKhachHang");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.KhachSan", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.LoaiPhong", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.NhanVien", b =>
                {
                    b.Navigation("ThongBaoNhanVien");
                });

            modelBuilder.Entity("BookingRoomHotel.Models.Phong", b =>
                {
                    b.Navigation("DatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
